INSERT INTO CLIENT (NOMBRE, APELLIDO, EDAD, FECHANACIMIENTO) VALUES ('Irving', 'Chero Garcia', 27, '1992-08-01');
INSERT INTO CLIENT (NOMBRE, APELLIDO, EDAD, FECHANACIMIENTO) VALUES ('Ingrid', 'Chero Garcia', 25, '1994-11-17');
INSERT INTO CLIENT (NOMBRE, APELLIDO, EDAD, FECHANACIMIENTO) VALUES ('Jose', 'Chero', 57, '1962-07-25');